name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t scarf-postgres-exporter:ci .

      - name: Smoke test with overridden workdir (simulates Actions)
        shell: bash
        run: |
          set +e
          # Run without required env so app exits early; we only assert error origin.
          OUTPUT=$(docker run --rm -w /github/workspace scarf-postgres-exporter:ci 2>&1)
          STATUS=$?
          echo "Container exit code: ${STATUS}"
          if [ "$STATUS" -eq 0 ]; then
            echo "ERROR: Container exited with code 0, but expected non-zero due to missing env var."
            exit 1
          fi
          echo "--- Begin Container Output ---"
          echo "$OUTPUT"
          echo "--- End Container Output ---"

          # Must NOT be an npm/package.json ENOENT error.
          if echo "$OUTPUT" | grep -Eqi "npm error|Could not read package.json|enoent.*package.json"; then
            echo "Unexpected npm/package.json error detected. Entry point fix failed."
            exit 1
          fi

          # Should fail fast due to missing env var from our app (expected in smoke test).
          if echo "$OUTPUT" | grep -q "missing env variable: SCARF_API_TOKEN"; then
            echo "Smoke test passed: entrypoint runs from /app and app executed."
            exit 0
          else
            echo "Did not observe expected app error. Output above for debugging."
            exit 1
          fi

      - name: Security regression check (no bash -c spawn)
        shell: bash
        run: |
          # Ensure we are not spawning a shell to run psql commands
          # Limit search to source files to avoid matching this workflow text
          if grep -R --include='*.ts' --include='*.js' -n -E "spawn\(['\"]bash['\"]" .; then
            echo "Found shell-based spawn usage. This is unsafe for connection strings with special characters."
            exit 1
          fi
          echo "No bash-based spawn usage detected."

      - name: Injection-safe psql invocation with special chars
        shell: bash
        run: |
          set +e
          # Use a connection string with a semicolon to simulate special characters in passwords
          OUTPUT=$(docker run --rm \
            -e SCARF_API_TOKEN=dummy \
            -e SCARF_ENTITY_NAME=dummy \
            -e PSQL_CONN_STRING='postgres://user:p%40ss;word@localhost:5432/dbname' \
            scarf-postgres-exporter:ci 2>&1)
          STATUS=$?
          echo "Container exit code: ${STATUS}"
          echo "--- Begin Output ---"
          echo "$OUTPUT"
          echo "--- End Output ---"

          # Must not show shell trying to execute -qtAX due to broken quoting
          if echo "$OUTPUT" | grep -q "-qtAX: command not found"; then
            echo "Detected unsafe shell splitting in psql invocation."
            exit 1
          fi
          echo "Psql invocation appears shell-safe."
