name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Run unit tests
        run: npm test

  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}
      sha: ${{ steps.meta.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Derive image ref
        id: meta
        run: |
          echo "image=${{ env.REGISTRY }}/${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (SHA tag)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
          tags: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.sha }}
      - name: Tag and push latest on main
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.image }}:latest

  container-tests:
    needs: [build-and-push-image]
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Smoke test with overridden workdir (simulates Actions)
        shell: bash
        env:
          IMAGE: ${{ needs.build-and-push-image.outputs.image }}
          SHA: ${{ needs.build-and-push-image.outputs.sha }}
        run: |
          set +e
          OUTPUT=$(docker run --rm -w /github/workspace "$IMAGE:$SHA" 2>&1)
          STATUS=$?
          echo "Container exit code: ${STATUS}"
          if [ "$STATUS" -eq 0 ]; then
            echo "ERROR: Container exited with code 0, but expected non-zero due to missing env var."
            exit 1
          fi
          echo "--- Begin Container Output ---"
          echo "$OUTPUT"
          echo "--- End Container Output ---"

          if echo "$OUTPUT" | grep -Eqi "npm error|Could not read package.json|enoent.*package.json"; then
            echo "Unexpected npm/package.json error detected. Entry point fix failed."
            exit 1
          fi
          if echo "$OUTPUT" | grep -q "missing env variable: SCARF_API_TOKEN"; then
            echo "Smoke test passed: entrypoint runs from /app and app executed."
          else
            echo "Did not observe expected app error. Output above for debugging."
            exit 1
          fi

      - name: Security regression check (no bash -c spawn)
        run: bash scripts/check_no_shell_spawn.sh

      - name: Injection-safe psql invocation with special chars
        run: bash scripts/test_psql_injection.sh "${{ needs.build-and-push-image.outputs.image }}:${{ needs.build-and-push-image.outputs.sha }}"

  range-guard:
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run range guard
        run: bash scripts/range_guard.sh "${{ needs.build-and-push-image.outputs.image }}:${{ needs.build-and-push-image.outputs.sha }}"

  export-scarf-data:
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: scarf
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run exporter against Postgres with real API
        if: ${{ secrets.SCARF_API_TOKEN != '' && secrets.SCARF_ENTITY_NAME != '' }}
        env:
          SCARF_API_TOKEN: ${{ secrets.SCARF_API_TOKEN }}
          SCARF_ENTITY_NAME: ${{ secrets.SCARF_ENTITY_NAME }}
          BACKFILL_DAYS: "1"
          PSQL_CONN_STRING: 'postgres://postgres:pass@postgres:5432/scarf'
          IMAGE: ${{ needs.build-and-push-image.outputs.image }}
          SHA: ${{ needs.build-and-push-image.outputs.sha }}
        run: |
          docker run --rm \
            -e SCARF_API_TOKEN \
            -e SCARF_ENTITY_NAME \
            -e BACKFILL_DAYS \
            -e PSQL_CONN_STRING \
            "$IMAGE:$SHA"
      - name: Verify row imported
        if: ${{ secrets.SCARF_API_TOKEN != '' && secrets.SCARF_ENTITY_NAME != '' }}
        run: bash scripts/verify_import_count.sh "postgres://postgres:pass@localhost:5432/scarf"
